object Libs {
    const val APP_COMPAT = "androidx.appcompat:appcompat"
    const val CORE_KTX = "androidx.core:core-ktx"
    const val LIFECYCLE_EXTENSION = "androidx.lifecycle:lifecycle-extensions"
    const val LIFECYCLE_RUN_TIME = "androidx.lifecycle:lifecycle-runtime-ktx"
    const val COMPOSE_UI = "androidx.compose.ui:ui"
    const val COMPOSE_UI_GRAPHICS = "androidx.compose.ui:ui-graphics"
    const val COMPOSE_UI_TOOLING = "androidx.compose.ui:ui-tooling"
    const val COMPOSE_FOUNDATION_LAYOUT = "androidx.compose.foundation:foundation-layout"
    const val COMPOSE_MATERIAL = "androidx.compose.material:material"
    const val COMPOSE_RUNTIME_LIVEDATA = "androidx.compose.runtime:runtime-livedata"
    const val COMPOSE_RUNTIME = "androidx.compose.runtime:runtime"
    const val COMPOSE_ANIMATION = "androidx.compose.animation:animation"
    const val COMPOSE_ANIMATION_CORE = "androidx.compose.animation:animation-core"
    const val COMPOSE_NAVIGATION = "androidx.navigation:navigation-compose"
    const val COMPOSE_ACTIVITY = "androidx.activity:activity-compose"
    const val COMPOSE_CONSTRAINT = "androidx.constraintlayout:constraintlayout-compose"
    const val COMPOSE_ICON = "androidx.compose.material:material-icons-extended"
    const val COMPOSE_TEST = "androidx.compose.ui:ui-test-junit4:1.0.0-rc01"
    const val COMPOSE_VIEW_MODEL = "androidx.lifecycle:lifecycle-viewmodel-compose"
    const val INSETS = "com.google.accompanist:accompanist-insets"
    const val COIL = "com.google.accompanist:accompanist-coil"
    const val KOIN_CORE = "io.insert-koin:koin-core"
    const val KOIN_ANDROID = "io.insert-koin:koin-android"
    const val KOIN_COMPOSE = "io.insert-koin:koin-androidx-compose"
    const val KOIN_KTOR = "io.insert-koin:koin-ktor"
    const val KOIN_LOGGER = "io.insert-koin:koin-logger-slf4j"
    const val COROUTINES = "org.jetbrains.kotlinx:kotlinx-coroutines-core"
    const val KTOR_CORE = "io.ktor:ktor-client-core"
    const val KTOR_JSON = "io.ktor:ktor-client-json"
    const val KTOR_LOGGING = "io.ktor:ktor-client-logging"
    const val KTOR_SERIALIZATION = "io.ktor:ktor-client-serialization"
    const val KTOR_ANDROID = "io.ktor:ktor-client-android"
    const val KOTLIN_SERIALIZATION = "org.jetbrains.kotlinx:kotlinx-serialization-core"

}